version: '3'

services: 
  express_backend:
    container_name: express_backend
    build: 
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes: 
      - ./:/app

  postgres:
    container_name: postgres
    build: 
      context: .
      dockerfile: postgres.Dockerfile      
    ports:
      - 5432:5432
    
  # my_lab:
  #   container_name: my_lab 
  #   image: 'jupyter/base-notebook'
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - JUPYTER_ENABLE_LAB=yes
  #   volumes:
  #     - ./test:/home/jovyan/work